# This file is docker-compose override file, cf.
# https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
# It is use in conjunction with docker-compose.yml core file to add a specific configuration
# to set up an Squid proxy to accelerate plugins downloads during Evergreen development.
# This file is automatically used by the tests/*tests.sh files.
#
# To disable it, define the "DISABLE_PROXY_CACHE" environment variable as follows:
# export DISABLE_PROXY_CACHE=true
version: '3'
services:

  instance:
    environment:
      - 'HTTP_PROXY=http://cache:3128'
      - 'http_proxy=http://cache:3128'
      - 'NO_PROXY=localhost,127.0.0.1'
      - 'no_proxy=localhost,127.0.0.1'

  cache:
    image: sameersbn/squid:3.3.8-23
    ports:
      - '3128:3128'
    volumes:
      - squid-cache:/var/spool/squid3
      - ./config/squid.conf:/etc/squid3/squid.conf:ro
volumes:
  squid-cache:
    external: true
