version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - 'POSTGRES_PASSWORD=grassisevergreener'
      # Used for psql non-interactive scripting
      - 'PGPASSWORD=grassisevergreener'
      - 'POSTGRES_DB=evergreen_development'
    ports:
      - '5432:5432'

  node:
    image: node:9-alpine
    command: 'npm run start'
    working_dir: $PWD
    environment:
      - 'PATH=$PWD/node_modules/.bin:$PATH'
      - 'DB_TRACING=$DB_TRACING'
      - 'DEBUG=$DEBUG'
    volumes:
      - $PWD:$PWD
    ports:
      - '3030:3030'
    depends_on:
      - db
