---
jenkins:
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "tcp://localhost:2375/"
        templates:
          - labelString: "agent"
            dockerTemplateBase:
              image: "jenkins/slave"
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"
